application: dance-wiki
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /gae-wiki-static/
  static_dir: gaewiki/static
- url: /favicon.ico
  static_files: gaewiki/static/favicon.ico
  upload: gaewiki/static/favicon.ico
- url: .*
  script: gaewiki.application

libraries:
- name: django
  version: "1.2"
- name: webob
  version: "1.2.3"